Add request exist reviewers for github-request-review

diff --git a/github-request-review b/github-request-review
--- a/github-request-review
+++ b/github-request-review
@@ -31,7 +31,13 @@ if [[ $# = 1 && $1 = -h ]]; then
     exit
 fi
 
-reviewer=${1?expected a reviewer arg}
+req_opts=(--json url)
+
+if [ -t 0 ] && [ -t 2 ] && [ -z "${1-}" ]; then
+    req_opts+=(--json reviews)
+else
+    reviewer=${1?required a reviewer arg}
+fi
 method=POST
 shift
 
@@ -41,11 +47,20 @@ for arg; do case "$arg" in
     *) args+=("$arg");;
 esac done
 
-url=$(gh pr view --json url "${args[@]}" | jq -r .url || exit)
+meta=$(gh pr view "${req_opts[@]}" "${args[@]}" |
+    jq -r '.url, ([.reviews[]?.author.login] | unique[])' || exit)
+mapfile -t meta <<< "$meta"
+
+url=${meta[0]}
 number=${url##*/}
 api=/repos${url##*github.com}
 api=${api%pull/*?}pulls/$number/requested_reviewers
 echo "${api@A}" >&2
+
+PS3="request reviewer> "; select reviewer in "${meta[@]:1}"; do
+    [ -n "$reviewer" ] && break
+    echo 'Invalid reviewer' >&2
+done || exit
 
 gh api --method $method \
     -H "Accept: application/vnd.github+json" \
